using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using TitanEditor.Character;

namespace TitanEditor.Premium
{
	// Token: 0x02000019 RID: 25
	public partial class Item_default : Form
	{
		// Token: 0x06000156 RID: 342 RVA: 0x0001257E File Offset: 0x0001077E
		public Item_default()
		{
			this.InitializeComponent();
		}

		// Token: 0x06000157 RID: 343 RVA: 0x0001258C File Offset: 0x0001078C
		protected byte[] loadInventory(string charName)
		{
			if (charName == "")
			{
				return null;
			}
			DBLite.dbMu.Read("select Inventory from DefaultClassType where Class = '" + charName + "'");
			DBLite.dbMu.Fetch();
			byte[] asBinary = DBLite.dbMu.GetAsBinary("Inventory");
			DBLite.dbMu.Close();
			return asBinary;
		}

		// Token: 0x06000158 RID: 344 RVA: 0x000125E8 File Offset: 0x000107E8
		private void Item_default_Load(object sender, EventArgs e)
		{
			this.Text = this.CharName + " Inventory - " + this.NameClass;
			this.charPanel1.Editor = this.equipEditor1;
			this.equipPanel1.setSize(8, 8);
			this.equipPanel1.Editor = this.equipEditor1;
			this.equipPanel2.setSize(8, 4);
			this.equipPanel2.Editor = this.equipEditor1;
			this.equipPanel3.setSize(8, 4);
			this.equipPanel3.Editor = this.equipEditor1;
			this.equipPanel4.setSize(8, 4);
			this.equipPanel4.Editor = this.equipEditor1;
			this.equipEditor1.LoadData();
			byte[] array = this.loadInventory(this.CharName);
			if (array != null)
			{
				this.charPanel1.clearData();
				if (!this.charPanel1.loadItemsByCodes(array, 0, 192))
				{
					MessageBox.Show(string.Format("[{0}] Error loading body equipment", this.CharName));
				}
				this.equipPanel1.clearData();
				if (!this.equipPanel1.loadItemsByCodes(array, 192, array.Length - 192 - this.equipPanel2.XNum * this.equipPanel2.YNum * 16))
				{
					MessageBox.Show(string.Format("[{0}] Error loading inventory equipment", this.CharName));
				}
				this.equipPanel2.clearData();
				if (!this.equipPanel2.loadItemsByCodes(array, 192 + this.equipPanel1.XNum * this.equipPanel1.YNum * 16, array.Length))
				{
					MessageBox.Show(string.Format("[{0}] Error loading inventory ex1 equipment", this.CharName));
				}
				this.equipPanel3.clearData();
				if (!this.equipPanel3.loadItemsByCodes(array, 192 + this.equipPanel1.XNum * this.equipPanel1.YNum * 16 + this.equipPanel2.XNum * this.equipPanel2.YNum * 16, array.Length))
				{
					MessageBox.Show(string.Format("[{0}] Error loading  inventory ex2 equipment", this.CharName));
				}
				this.equipPanel4.clearData();
				if (!this.equipPanel4.loadItemsByCodes(array, 192 + this.equipPanel1.XNum * this.equipPanel1.YNum * 16 + (this.equipPanel2.XNum * this.equipPanel2.YNum * 16 + this.equipPanel3.XNum * this.equipPanel3.YNum * 16) * 2, array.Length))
				{
					MessageBox.Show(string.Format("[{0}] Error loading pshop equipment", this.CharName));
				}
			}
		}

		// Token: 0x06000159 RID: 345 RVA: 0x00012890 File Offset: 0x00010A90
		private void button1_Click_1(object sender, EventArgs e)
		{
			new EquipPanel().setSize(8, 4);
			string query = string.Format("update DefaultClassType set Inventory=0x{0}{1}{2} where Class='{3}'", new object[]
			{
				this.charPanel1.getEquipCodes(),
				this.equipPanel1.getEquipCodes(),
				this.equipPanel2.getEquipCodes(),
				this.CharName
			});
			DBLite.dbMu.Exec(query);
			DBLite.dbMu.Close();
			MessageBox.Show("Inventory Edited", "Titan Editor", MessageBoxButtons.OK);
			base.Close();
		}

		// Token: 0x0600015A RID: 346 RVA: 0x0001291A File Offset: 0x00010B1A
		private void button2_Click_1(object sender, EventArgs e)
		{
			base.Close();
		}

		// Token: 0x0600015B RID: 347 RVA: 0x00012924 File Offset: 0x00010B24
		private void btn_reset_Click_1(object sender, EventArgs e)
		{
			DBLite.dbMu.Exec("UPDATE DefaultClassType SET Inventory=0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF WHERE Class = '" + this.CharName + "'");
			DBLite.dbMu.Close();
			MessageBox.Show("Inventario Reseteado", "Titan Editor", MessageBoxButtons.OK);
			base.Close();
			new Item
			{
				CharName = this.CharName
			}.ShowDialog();
		}

		// Token: 0x04000127 RID: 295
		public string CharName;

		// Token: 0x04000128 RID: 296
		public string NameClass;
	}
}
